[package]
name = "we8-platform"
version = "0.1.1"
description = "WE8 online arena desktop client"
authors = ["WEL Platform"]
edition = "2021"
rust-version = "1.77.2"

[build-dependencies]
cargo_toml = "=0.17.2"
tauri-build = { version = "=2.0.0", features = [] }

[lib]
name = "we8_platform_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "we8-platform"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "=2.0.0", features = [] }
tauri-codegen = "=2.0.0"
tauri-macros = "=2.0.0"
tauri-plugin-opener = "=2.0.0"
tauri-runtime = "=2.0.0"
tauri-runtime-wry = "=2.0.0"
tauri-utils = "=2.0.0"
